# Site settings
title: Hanchan Song
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hanchan Song
user_description: I'm a Postdoctoral Researcher from Texas A&M University
user_title: Semiconductor and AI algorithm Researcher
email: shcme12@gmail.com
# twitter_username: 
#instagram_username: 
#facebook_username: 
#linkedin_username: 
github_username:  rumigun
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

